# Generated by Django 4.2.3 on 2023-07-14 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageData',
            fields=[
                ('ipAddress', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('placeName', models.CharField(choices=[('start', 'start'), ('end', 'end'), ('qa', 'qa'), ('rework', 'rework')], max_length=6)),
                ('stageName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.line')),
            ],
        ),
    ]
