# Generated by Django 4.2.3 on 2023-07-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('line_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('line_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fg_code', models.CharField(max_length=10)),
                ('product_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('rejection_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('rejection_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rework',
            fields=[
                ('rework_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('rework_description', models.CharField(max_length=20)),
            ],
        ),
    ]
