# Generated by Django 4.2.3 on 2023-07-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='line_name',
            new_name='line_description',
        ),
    ]
