# Generated by Django 4.2.3 on 2023-07-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_line_name_line_line_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='processId',
            field=models.CharField(default='SMT', max_length=30),
            preserve_default=False,
        ),
    ]
