# Generated by Django 4.2.3 on 2023-07-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0002_rename_line_name_line_line_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('processNo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('currentQuantity', models.IntegerField()),
                ('maxQuantity', models.IntegerField()),
                ('tempStartingSno', models.CharField(max_length=12)),
                ('tempEndingSno', models.CharField(max_length=12)),
                ('permStartingSno', models.CharField(max_length=13)),
                ('permEndingSno', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessCard',
            fields=[
                ('processCardNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start', models.BooleanField(default=False)),
                ('end', models.BooleanField(default=False)),
                ('qa', models.BooleanField(default=False)),
                ('rework', models.BooleanField(default=False)),
                ('final', models.CharField(choices=[('start', 'start'), ('end', 'end'), ('qa', 'qa'), ('rework', 'rework')], max_length=6)),
                ('quantity', models.IntegerField()),
                ('processNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process')),
                ('stageName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.line')),
            ],
        ),
    ]
