# Generated by Django 4.2.3 on 2023-07-17 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_product_processid'),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='productCode',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data.product'),
            preserve_default=False,
        ),
    ]
