# Generated by Django 4.2.3 on 2023-07-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='userCode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
